---
- name: Copy index.html
  template:
    src: templates/index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify: reload nginx

- name: Copy default.conf
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: reload nginx
