MACHINES = {
  :'centos7' => {
              :box_name => 'centos/7',
              :cpus => 2,
              :memory => 2048,
              :net => [],
              :forwarded_port => [8080]
            }
}

Vagrant.configure('2') do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      if boxconfig.key?(:net)
        boxconfig[:net].each do |ipconf|
          box.vm.network 'private_network', ipconf
        end
      end
      if boxconfig.key?(:forwarded_port)
        boxconfig[:forwarded_port].each do |port|
          box.vm.network 'forwarded_port', guest: 8080, host: 8080
        end
      end
      box.vm.provider 'virtualbox' do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
    end
  end
end
