# frozen_string_literal: true

# Describe VMs
MACHINES = {
  # VM name "kernel update"
  "centos7": {
    box_name: 'centos/7',
    cpus: 2,
    memory: 2048,
    net: [],
    forwarded_port: []
  }
}.freeze

Vagrant.configure('2') do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      if boxconfig.key?(:net)
        boxconfig[:net].each do |ipconf|
          box.vm.network 'private_network', ipconf
        end
      end
      if boxconfig.key?(:forwarded_port)
        boxconfig[:forwarded_port].each do |port|
          box.vm.network 'forwarded_port', port
        end
      end
      box.vm.provider 'virtualbox' do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      box.vm.provision 'shell', inline: <<-SHELL
        yum install -y lsof
      SHELL
      box.vm.provision 'file', source: './ps-ax.sh', destination: '~/ps-ax.sh'
      box.vm.provision 'file', source: './concurrent/fibonacci.sh', destination: '~/fibonacci.sh'
      box.vm.provision 'file', source: './concurrent/nice_run_fibonacci.sh', destination: '~/nice_run_fibonacci.sh'
      box.vm.provision 'file', source: './concurrent/ionice_run_fibonacci.sh', destination: '~/ionice_run_fibonacci.sh'
    end
  end
end
